export const GET_FRESH_FRUITS_LOADING = "GET_FRESH_FRUITS_LOADING";
export const GET_FRESH_FRUITS_SUCCESS = "GET_FRESH_FRUITS_SUCCESS";
export const GET_FRESH_FRUITS_ERROR = "GET_FRESH_FRUITS_ERROR";

export const GET_EXOTIC_FRUITS_LOADING = "GET_EXOTIC_FRUITS_LOADING";
export const GET_EXOTIC_FRUITS_SUCCESS = "GET_EXOTIC_FRUITS_SUCCESS";
export const GET_EXOTIC_FRUITS_ERROR = "GET_EXOTIC_FRUITS_ERROR";

export const GET_COMBOS_FRUITS_LOADING = "GET_COMBOS_FRUITS_LOADING";
export const GET_COMBOS_FRUITS_SUCCESS = "GET_COMBOS_FRUITS_SUCCESS";
export const GET_COMBOS_FRUITS_ERROR = "GET_C0MBOS_FRUITS_ERROR";

export const GET_BEST_DEALS_LOADING = "GET_BEST_DEALS_LOADING";
export const GET_BEST_DEALS_SUCCESS = "GET_BEST_DEALS_SUCCESS";
export const GET_BEST_DEALS_ERROR = "GET_BEST_DEALS_ERROR";

export const GET_SINGLE_PRODUCT_LOADING = "GET_SINGLE_PRODUCT_LOADING";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR  ";
