export const GET_FRESH_FRUITS_LOADING = "GET_FRESH_FRUITS_LOADING";
export const GET_FRESH_FRUITS_SUCCESS = "GET_FRESH_FRUITS_SUCCESS";
export const GET_FRESH_FRUITS_ERROR = "GET_FRESH_FRUITS_ERROR";

export const GET_EXOTIC_FRUITS_LOADING = "GET_EXOTIC_FRUITS_LOADING";
export const GET_EXOTIC_FRUITS_SUCCESS = "GET_EXOTIC_FRUITS_SUCCESS";
export const GET_EXOTIC_FRUITS_ERROR = "GET_EXOTIC_FRUITS_ERROR";

export const GET_COMBOS_FRUITS_LOADING = "GET_COMBOS_FRUITS_LOADING";
export const GET_COMBOS_FRUITS_SUCCESS = "GET_COMBOS_FRUITS_SUCCESS";
export const GET_COMBOS_FRUITS_ERROR = "GET_C0MBOS_FRUITS_ERROR";
